site_name: pyDARNio Documentation
repo_url: https://github.com/superdarn/pyDARNio
theme: readthedocs
markdown_extensions:
    - extra
    - admonition
    - toc

nav:
    - Home: index.md
    - About: about.md
    - Installation: user/install.md  
    - SuperDARN Data Access: user/superdarn_data.md 
    - Citing: user/citing.md
    - Tutorials:
        - IO:
            - SuperDARN (DMAP) files: user/SDarn.md
            - Borealis files: user/BorealisIO.md
        - Convert: 
            - Borealis to SuperDARN (DMAP): user/Borealis2SuperDARN.md
        - Radar and Hardware Information: user/hardware.md 
